### ISSUE TITLE
Flatpak installation fatally fails if there is an error during installtion of optional extension 

### ISSUE THREAD

**Issue by arshubham** [elementary/appcenter#1086]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Unable to install some flatpaks like Celluloid, dconf-editor via flatpak. I am on a fresh install with master for appcenter and on the latest flatpak from ppa:alexlarsson/flatpak. `runtime/org.freedesktop.Platform.openh264/x86_64/19.08` seems to be offending package here. Could also reproduce before reinstall. FlatHub is the only remote added.

![Screen record from 2019-09-25 23 29 44](https://user-images.githubusercontent.com/14235191/65627167-6ddd3400-dfec-11e9-9680-a50368683ea5.gif)

### Expected behavior
The application should be installed as it is by the terminal.

### Logs
```
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:08:59.856: Fetching summary file for remote ‘flathub’
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:08:59.995: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.042: Transaction: install flathub:app/io.github.celluloid_player.Celluloid/x86_64/stable[*]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.042: Updating remote metadata for flathub
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.043: marking op install:app/io.github.celluloid_player.Celluloid/x86_64/stable resolved to b451ecd6000273a53b681889be4eca371852059d123388aada200301d25ced71
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.043: Updating dependent runtime runtime/org.gnome.Platform/x86_64/3.34
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.043: Transaction: update flathub:runtime/org.gnome.Platform/x86_64/3.34[$old]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.043: marking op update:runtime/org.gnome.Platform/x86_64/3.34 resolved to c71ff4eca043963072f57479f28fb9094ff1c93e54f26d9e6a6f86c1c116c9af
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.043: No installations directory in /etc/flatpak/installations.d. Skipping
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.105: Transaction: install/update flathub:runtime/org.gnome.Platform.Locale/x86_64/3.34[/en]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.105: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/19.08[*]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.105: Transaction: install/update flathub:runtime/org.gtk.Gtk3theme.elementary/x86_64/3.22[*]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.105: Transaction: install/update flathub:runtime/org.freedesktop.Platform.openh264/x86_64/19.08[$old]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.109: Transaction: install/update flathub:runtime/io.github.celluloid_player.Celluloid.Locale/x86_64/stable[/en]
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.109: marking op install/update:runtime/io.github.celluloid_player.Celluloid.Locale/x86_64/stable resolved to a5f8c441f5acf86f4d719f0dd04e67847e0eaeea82310927cf436f5597a119cd
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.109: marking op install/update:runtime/org.freedesktop.Platform.openh264/x86_64/19.08 resolved to c0062d844eea58356fd6a153a29725c7fef7ee91df53ac759a535d1e5ee27a03
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.109: marking op install/update:runtime/org.gtk.Gtk3theme.elementary/x86_64/3.22 resolved to 454d1cade4c0bd660e6f60eef0223891cb61627ba8816de8bfc15aba4240cbbb
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.109: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/19.08 resolved to b305a18e211d96744ab1e03d074566214f7bcae5a1e4978455519e024d28fb93
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.109: marking op install/update:runtime/org.gnome.Platform.Locale/x86_64/3.34 resolved to c4f52b95b217ea57b093089b466aae2885bcaa4aff46cade2f262fa548206a60
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.110: Calling system helper: GetRevokefsFd
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.110: Calling system helper: GetRevokefsFd
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:00.131: Preparing transaction in repository 0x55ded04c39f0
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:00.131: Using new tmpdir staging-e2393f44-da86-44c0-9a1f-130a3af5ca19-j69FCd
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:00.131: flatpak_dir_pull: Using commit c0062d844eea58356fd6a153a29725c7fef7ee91df53ac759a535d1e5ee27a03 for pull of ref runtime/org.freedesktop.Platform.openh264/x86_64/19.08 from remote flathub
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:01.069: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:01.148: starting fetch of c0062d844eea58356fd6a153a29725c7fef7ee91df53ac759a535d1e5ee27a03.commit (detached)
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:01.288: fetch of c0062d844eea58356fd6a153a29725c7fef7ee91df53ac759a535d1e5ee27a03.commit (detached) complete
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:01.288: _ostree_fetcher_should_retry_request: error: unset, n_retries_remaining: 5
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:01.289: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:01.312: pull: idle, exiting mainloop
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:01.314: Loading https://github.com/cisco/openh264/releases/download/v2.0.0/libopenh264-2.0.0-linux64.5.so.bz2 using libsoup
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:03.932: Received 592986 bytes
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:03.946: Committing transaction in repository 0x55ded04c39f0
(io.elementary.appcenter:4798): OSTree-DEBUG: 23:09:03.946: txn commit staging-e2393f44-da86-44c0-9a1f-130a3af5ca19-j69FCd
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:04.020: Calling system helper: Deploy

** (io.elementary.appcenter:4798): WARNING **: 23:09:04.216: FlatpakBackend.vala:613: Flatpak installation failed: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed
(io.elementary.appcenter:4798): flatpak-DEBUG: 23:09:04.217: Fetching summary file for remote ‘flathub’
```
## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context
Can successfully install it via terminal. 
![Screenshot from 2019-09-25 23 24 10](https://user-images.githubusercontent.com/14235191/65626803-ae887d80-dfeb-11e9-9946-561af52661ac.png)

**Comment by TingPing** [comment]
This is fixed in a `flatpak` update https://bugs.launchpad.net/ubuntu/+source/flatpak/+bug/1844666

But also appcenter should not be fatally failing for an optional extension.

**Comment by arshubham** [comment]
@TingPing In am on Version 1.4.3 for flatpak and still facing the issue.

**Comment by TingPing** [comment]
Hmm, indeed the logs show it starting the proper download.

**Comment by ahayzen** [comment]
I think the issue with 1.4.3 might be related to https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886
