### ISSUE TITLE
AppCenter updates count always showing zero (0) on plank.

### ISSUE THREAD

**Issue by queeup** [elementary/appcenter#1136]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
AppCenter updates counts always showing zero (0) on plank.

### Expected behavior
In the example below, plank should show 1 update on the AppCenter icon.

### Screenshots or screen recordings

![2019-11-15 13-27-15 ekran görüntüsü](https://user-images.githubusercontent.com/87835/68937334-3e0d0a00-07ad-11ea-9763-1e8ab3a52cb1.png)

![2019-11-16 17-52-49 ekran görüntüsü](https://user-images.githubusercontent.com/87835/69000124-f769fd80-08db-11ea-86e4-c79ddc868953.png)

## Platform Information
 - OS: elementary OS
 - OS Version: Juno
 - Hardware info: Thinkpad T430

- [X] I'm using the latest released stable version

## Additional context
```console
appcenter:	3.2.0+r2067+pkg81~ubuntu5.0.1
plank:	        0.11.4+git20190318.fb624c21-0elementary5.0.1
```

**Comment by vjr** [comment]
In my case, there are updates showing in the app window with the badge there but on the plank icon there is no badge showing. I'm guessing some race condition in the `updates_number` being set in the calls to async `refresh_updates ()` https://github.com/elementary/appcenter/blob/22cc4ca358c7bceb3cc337dc7caec64afa17ae40/src/Core/Client.vala#L64

**Comment by 4jNsY6fCVqZv** [comment]
@vjr I'm afraid I can't tell if your guess is correct. But I also have the problem with two computers that the badge on the plank icon is not shown at all.

**Comment by Julioevm** [comment]
I've been havin this issue lately. Definitely didn't happen before 'hera' to me.

**Comment by egee-irl** [comment]
This has been happening to me since I installed 5.1. I have a strong hunch this has something to do with the Flatpak integration.

When there are Flatpak updates, the AppCenter shows up in my dock with the badge showing "0" updates. When I open AppCenter and go to updates, AppCenter says there's like 2gb worth of updates but only shows 2 _Flatpak_ apps that need updating.

After I update, suddenly there's like 5 or 6 more non-Flatpak apps that need updates and the update badge on the dock suddenly shows however many apps need updating.

I haven't dug much deeper into this issue because it's little more than annoying but I'm a bit surprised that nobody else is really talking about it.

**Comment by KomalleanaByzantis** [comment]
I hope that my report can contribute to this issue.

----

# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the bug

When updates are available and AppCentre is not pinned to the Dock, the AppCentre icon shows a red dot with zero updates.

## To reproduce

1. Wait for AppCentre to in the background check for updates.
2. Assuming that at least one component is outdated, the AppCentre icon is updated to show a red dot which contains a non-zero number of available updates. Right click the icon and unpin it from the Dock.
3. Restart the system and log in.
4. Wait for AppCentre to in the background again check for updates.
5. The AppCentre icon is updated to show a red dot which contains the number zero.

Note that this error can, as far as I can tell, only be reproduced once per user session.

## Expected behaviour

The AppCentre icon always shows the correct number of available updates.

## Screenshots or screen recordings

[Steps 1 and 2](https://mega.nz/#!47QSSIbK!O3Y7bQJ9s_2SNgc7zxELC66TDPTt7npGdIuyRQ0snrk)
[Steps 4 and 5](https://mega.nz/#!1nYWnKAT!N5DsfjJXJ6Y5jVXqwtVM9nz2-ZY1tHX6XWOfXi_TuUI)

# Platform information

Operating system: elementary OS
Version: 5.1 Hera

- [ ] I am using the latest version from GitHub which I have manually compiled
- [x] I am using the latest released stable version

System image used during the installation: elementaryos-5.1-stable.20191202.iso
Memory: 8 gigabytes
Disk space: ~10 gigabytes

Computer name: essai
Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

# Additional context

The testing system is installed on a small partition on a ThinkPad T470 laptop. Aside from specifying the language, keyboard, location, initial user, computer name, and the specific partition in which to install the system, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system is able to connect to the Internet via a wireless connection and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

Before this test was performed, the following steps were followed:

- All system components were updated via the blue “Update All” button in AppCentre.
- A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
- The current user was logged out and the new user was logged in.
- The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
- The computer was rebooted.
- The test user was logged in.

After the test, all system-wide changes (if any) which were made during the test have been reverted.

**Comment by hanaral** [comment]
The issue still persists on the newest version, though it only seems to happen when the appcenter has not yet loaded the actual updates page. In theory, maybe it could check how many there are when the appcenter first launches in the background?

**Comment by Julioevm** [comment]
I can confirm this issue persists.

**Comment by davidmhewitt** [comment]
There has been a PR merged that potentially improves/fixes this issue: https://github.com/elementary/appcenter/pull/1298

If anyone that can reproduce the issue is comfortable building and installing AppCenter from source using the instructions in the README and then rebooting, feel free to do so and report back on the results.

You can always re-install the stable/released version of AppCenter after doing this using the command:
`sudo apt install --reinstall appcenter`

**Comment by hanaral** [comment]
I’ve been testing it, and it seems to be fixed. I will edit this if I find otherwise @davidmhewitt

**Comment by hanaral** [comment]
@davidmhewitt I have updated the comment

**Comment by eliocamp** [comment]
I'm having a similar issue, but in my case the badge shows 1 update available even thought there are no updates. The issue persists even through reboots. 

![image](https://user-images.githubusercontent.com/8617595/84167981-44b2e580-aa4d-11ea-9b51-8051be988039.png)

**Comment by davidmhewitt** [comment]
@eliocamp Can you run AppCenter with debugging output by running the following commands and then copy and paste the output:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

**Comment by eliocamp** [comment]
Killing the app reseted the badge. Then it took a while to look for updates and now again it shows the 1 update badge even though there is no update listed. However, now closing the app does remove the Plank icon. 

Here's the result:
https://pastebin.com/8g41GrBU

**Comment by davidmhewitt** [comment]
@eliocamp Great, that helps a lot, thanks.

It looks like there is a Flatpak update that AppCenter isn't able to show for some reason.

If you run `flatpak update` in the terminal, you should be able to clear it.

**Comment by eliocamp** [comment]
Yes! It's now fixed. Thanks!

**Comment by cassidyjames** [comment]
This should have been fixed by recent AppCenter updates. If it crops again again, feel free to comment and we can re-open.

**Comment by eliocamp** [comment]
I'm still having some issues with the update indicator. Now when it does its auto update, it shows the notification on Plank, but with zero, even though the notification on the top right does display the correct number. 

![image](https://user-images.githubusercontent.com/8617595/102620898-87046000-411d-11eb-98c8-ea556ebeee71.png)
![image](https://user-images.githubusercontent.com/8617595/102620984-abf8d300-411d-11eb-907e-036ff9196474.png)

Then, if I open AppCenter it updates again before showing me the actual updates and now Plank displays the correct number too.

**Comment by hanaral** [comment]
I'm not able to reproduce it, so I presume it is fixed in the Odin version.

**Comment by queeup** [comment]
It's happening again on my stable odin install. @cassidyjames, please reopen this.

**Comment by cassidyjames** [comment]
@queeup can you provide more information about what happened before you experienced it again? Do you have a third-party Flatpak remote added? What shows up when you run `flatpak update` in Terminal?

**Comment by queeup** [comment]
```bash
❯ LC_ALL=C flatpak remote-list 
Name        Options
appcenter   system
flathub     system
freedesktop system,filtered
appcenter   user
flathub     user
```

![update_badge_bug](https://user-images.githubusercontent.com/87835/130697697-5d71896a-89d9-455a-8b4d-bbb4c0b5b8fe.png)

![update_badge_bug2](https://user-images.githubusercontent.com/87835/130697773-c64cd610-60c7-4ba8-a1e6-47880206f181.png)

**Comment by Gabriel-p** [comment]
Same here on Odin

```
$ LC_ALL=C flatpak remote-list
Name        Options
appcenter   system
freedesktop system,filtered
appcenter   user
flathub     user
```

**Comment by Gabriel-p** [comment]
Still happening in Horus

![Captura de pantalla de 2023-02-22 08 47 45](https://user-images.githubusercontent.com/6054951/220611504-1f9477f5-1e92-41cb-b4c4-23658b269fa2.png)

**Comment by CodingSpiderFox** [comment]
> Still happening in Horus
> 
> ![Captura de pantalla de 2023-02-22 08 47 45](https://user-images.githubusercontent.com/6054951/220611504-1f9477f5-1e92-41cb-b4c4-23658b269fa2.png)

Can confirm this, too. After logging in it showed a red bubble with "0". Then opened appcenter and clicked that orange icon on the top.
![image](https://user-images.githubusercontent.com/25173078/222883817-3a745954-2bd4-4dae-86dc-cde0210d8a68.png)

But I decided to not install the updates right now. 
Closed app center. Few seconds later, the count on the icon switched to "2"
