### ISSUE TITLE
More apps don't load when lists are super tall

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1445]
If the window is sized taller than the 21 results in a list, it's not currently possible to load more results in.

>If the page size on the scrolled vadjustment is equal to its upper bound, then we know all of the available rows are visible.
>
>I've just tried to call the show more apps function when that's the case and it gets called correctly when more apps are needed and the rows are added, but for some reason they're not visible.
>—@davidmhewitt

See: https://github.com/pop-os/shop/issues/233

**Comment by danrabbit** [comment]
This is fixed now that we use a grid view for categories instead of a list view

**Comment by jacobgkau** [comment]
@danirabbit The issue is still present with search results:

![Screenshot from 2023-10-09 12-27-57](https://github.com/elementary/appcenter/assets/7199422/60b75816-959d-4f62-8f25-58c96202009d)

After making the window smaller and scrolling to the bottom, more results do load in. Can we please re-open this issue?

**Comment by danirabbit** [comment]
@jacobgkau Are you perhaps running Pop Shop and not AppCenter? This was fixed for search in the latest release of AppCenterl: https://github.com/elementary/appcenter/pull/2076

**Comment by jacobgkau** [comment]
Sorry, we just got around to rebasing on 7.3.0 last month and I didn't realize another release happened at the same time. Good to see the actual fix.
