### ISSUE TITLE
DEP-11 Metadata Hash Sum Mismatch

### ISSUE THREAD

**Issue by delmartechdude** [elementary/appcenter#630]
Seeing this when I do a `sudo apt update`:

```
Get:15 http://packages.elementary.io/appcenter xenial/main amd64 Packages [59.3 kB]                                                      
Get:16 http://packages.elementary.io/appcenter xenial/main amd64 DEP-11 Metadata [55.6 kB]                                               
Err:16 http://packages.elementary.io/appcenter xenial/main amd64 DEP-11 Metadata                                                         
  Hash Sum mismatch
Get:17 http://packages.elementary.io/appcenter xenial/main DEP-11 64x64 Icons [223 kB]

E: Failed to fetch http://packages.elementary.io/appcenter/dists/xenial/main/dep11/Components-amd64.yml.xz  Hash Sum mismatch
```
This is new. I haven't changed anything as far as I'm aware.

**Comment by mIcHyAmRaNe** [comment]
it seems that it has been resolved.

i got the same error yesterday and this morning but now everything work well

**Comment by danrabbit** [comment]
Sorry, we were trying to make caching more efficient. Should be fixed now. Closing :)

**Comment by feryardiant** [comment]
Still having this issue on fresh install Elementary OS Juno using `elementaryos-5.0-stable.20181016.iso` downloaded earlier this week.

```
$ sudo apt update
Get:1 http://packages.elementary.io/appcenter bionic InRelease [5.894 B]
Hit:2 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                                                     
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                      
Hit:4 http://id.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                           
Hit:5 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                                                                                  
Get:6 http://packages.elementary.io/appcenter bionic/main amd64 Packages [67,7 kB]                                                                               
Get:7 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [174 kB]                                                                          
Err:7 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata                                                                         
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:174004 [weak]
   - SHA256:4723c4d3029dc5c92a31225260d0669a9cebb44ee041298b138687c35bbacca2
   - SHA1:73819f2bbb942a799106fd038bdbf7bd844960ea [weak]
   - MD5Sum:88b4f01fd19132c64191060cfa6a704e [weak]
  Hashes of received file:
   - SHA256:7451dd3c3e174f5463b8c4074506592cbb19f9f91e8f44512e64538aee3ecb4e
   - SHA1:0cd91d27bf43f48c8a4f3df51c6d5976d6e04ac9 [weak]
   - MD5Sum:0b52a71619133bf804ea4d1cbf25fc1d [weak]
   - Filesize:174004 [weak]
  Last modification reported: Sun, 14 Jul 2019 14:39:04 +0000
  Release file created at: Mon, 15 Jul 2019 14:24:14 +0000
Hit:8 http://id.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                              
Get:9 http://packages.elementary.io/appcenter bionic/main DEP-11 64x64 Icons [358 kB]                                
Hit:10 http://archive.canonical.com/ubuntu bionic InRelease                                         
Get:11 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]                                 
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]                                             
Get:13 http://packages.elementary.io/appcenter bionic/main DEP-11 64x64@2 Icons [752 kB]    
Get:14 http://packages.elementary.io/appcenter bionic/main DEP-11 128x128 Icons [754 kB]                    
Get:11 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]                                                                                                                                                                  
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [450 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [339 kB]                                                                                                                                                          
Get:17 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [571 kB]                                                                                                                                                     
Get:18 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [564 kB]                                                                                                                                                      
Fetched 4.174 kB in 2min 50s (24,6 kB/s)                                                                                                                                                                                                      
Reading package lists... Done
E: Failed to fetch http://packages.elementary.io/appcenter/dists/bionic/main/dep11/Components-amd64.yml.xz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:174004 [weak]
    - SHA256:4723c4d3029dc5c92a31225260d0669a9cebb44ee041298b138687c35bbacca2
    - SHA1:73819f2bbb942a799106fd038bdbf7bd844960ea [weak]
    - MD5Sum:88b4f01fd19132c64191060cfa6a704e [weak]
   Hashes of received file:
    - SHA256:7451dd3c3e174f5463b8c4074506592cbb19f9f91e8f44512e64538aee3ecb4e
    - SHA1:0cd91d27bf43f48c8a4f3df51c6d5976d6e04ac9 [weak]
    - MD5Sum:0b52a71619133bf804ea4d1cbf25fc1d [weak]
    - Filesize:174004 [weak]
   Last modification reported: Sun, 14 Jul 2019 14:39:04 +0000
   Release file created at: Mon, 15 Jul 2019 14:24:14 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Also the error message appeared every time I open appcenter

![image](https://user-images.githubusercontent.com/508665/61224662-2e22e200-a749-11e9-8b54-43d72f6ae0b9.png)

The only way to get rid the error message is by disabling appcenter repo listed on `/etc/apt/sources.list.d/appcenter.list`

```
# deb http://packages.elementary.io/appcenter bionic main
```

The problem is, I can't install or even seeing any curated apps through appcenter, only built-in apps and non-curated apps are listed

![image](https://user-images.githubusercontent.com/508665/61224737-54e11880-a749-11e9-933c-0db36a639b2b.png)

Any solution?

**Comment by cassidyjames** [comment]
@feryardiant, what country are you in? It's possible our AppCenter server is being blocked at a network or even country level… and yes, disabling the AppCenter repo would in fact mean that you would lose curated AppCenter apps. :wink:

**Comment by feryardiant** [comment]
Thanks for reply @cassidyjames 

Me from Indonesia and yes this country has so many network restriction 😅, but I'm not sure if that was the case causing my issue since I always using dns-crypt proxy, also I never had similar issue on other linux distros.

Any suggestion or solution is appreciated 😬

**Comment by hibbann** [comment]
@feryardiant 
I'm from Indonesia and i get this problem too. Someone on facebook group "ElementaryOS Indonesia" told me this thread..

Thank you for your attention and reply @cassidyjames
Please tell us how to fix this.
Thank You

**Comment by feryardiant** [comment]
> Someone on facebook group "ElementaryOS Indonesia" told me this thread..

And that was me, 🤣

**Comment by feryardiant** [comment]
Anyway, just re-check my installation (on VM) and the error still remain but the curated apps are shown,

<details>
 <summary><code>E: Failed to fetch http://packages.elementary.io/appcenter/dists/bionic/main/dep11/Components-amd64.yml.xz  File has unexpected size (181068 != 181064). Mirror sync in progress?</code></summary>

```
$ sudo apt update
Get:1 http://packages.elementary.io/appcenter bionic InRelease [5.894 B]
Hit:2 http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic InRelease                                                                 
Get:3 http://packages.elementary.io/appcenter bionic/main amd64 Packages [69,4 kB]                                                         
Get:4 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [181 kB]                                                                          
Get:4 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [181 kB]                                                                          
Get:4 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [181 kB]                                                                          
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                   
Hit:9 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                             
Hit:10 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                         
Get:4 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata [181 kB]                                                                            
Err:4 http://packages.elementary.io/appcenter bionic/main amd64 DEP-11 Metadata                                                   
  File has unexpected size (181068 != 181064). Mirror sync in progress? [IP: 104.28.5.44 80]
  Hashes of expected file:
   - Filesize:181064 [weak]
   - SHA256:090ff4f13eb7c69f486c74858e671006b1102f0aa5eb058ad09680adc5da6cee
   - SHA1:a68822fa9bb6dfb8ff201f10f03d1f231774084b [weak]
   - MD5Sum:45abc88b2c307e82a4dbba68b1461789 [weak]
  Release file created at: Mon, 22 Jul 2019 22:10:38 +0000
Hit:11 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                                      
Hit:12 http://id.archive.ubuntu.com/ubuntu bionic-updates InRelease                            
Hit:13 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                
Hit:14 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                
Hit:15 http://id.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Reading package lists... Done                       
E: Failed to fetch http://packages.elementary.io/appcenter/dists/bionic/main/dep11/Components-amd64.yml.xz  File has unexpected size (181068 != 181064). Mirror sync in progress? [IP: 104.28.5.44 80]
   Hashes of expected file:
    - Filesize:181064 [weak]
    - SHA256:090ff4f13eb7c69f486c74858e671006b1102f0aa5eb058ad09680adc5da6cee
    - SHA1:a68822fa9bb6dfb8ff201f10f03d1f231774084b [weak]
    - MD5Sum:45abc88b2c307e82a4dbba68b1461789 [weak]
   Release file created at: Mon, 22 Jul 2019 22:10:38 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
</details>

![image](https://user-images.githubusercontent.com/508665/61668009-bbe06d80-ad05-11e9-8865-67279cd1b8c2.png)

and I could even install them

![image](https://user-images.githubusercontent.com/508665/61668139-11b51580-ad06-11e9-905e-247b63cd9276.png)

**Comment by bilalbayasut** [comment]
@feryardiant solusinya gimana ya ini ?

can anyone share solution for this ?

**Comment by AbidKhairyAK** [comment]
> @feryardiant solusinya gimana ya ini ?
> 
> can anyone share solution for this ?

Same here, i'm indonesian too.

fixed this by running `apt` update like this

`apt update -o Acquire::CompressionTypes::Order::=gz`

**Comment by effendikiki** [comment]
> > @feryardiant solusinya gimana ya ini ?
> > can anyone share solution for this ?
> 
> Same here, i'm indonesian too.
> 
> fixed this by running `apt` update like this
> 
> `apt update -o Acquire::CompressionTypes::Order::=gz`

this command works in my machine, thanks!!

**Comment by keyxmakerx** [comment]
This happened on my main machine, though i'm unsure as to why. The fix above worked, but I'm curious as to what the cause is?
